env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
overrides: []
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  project:
    - './tsconfig.eslint.json'
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - '.vue'
plugins:
  - vue
  - '@typescript-eslint'
rules:
  vue/html-indent:
    - error
    - 2
  'vue/multi-word-component-names':
    - off
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline